In [184]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB

In [186]:
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [187]:
df.fillna("", inplace=True)
df.isnull().sum()

Disease       0
Symptom_1     0
Symptom_2     0
Symptom_3     0
Symptom_4     0
Symptom_5     0
Symptom_6     0
Symptom_7     0
Symptom_8     0
Symptom_9     0
Symptom_10    0
Symptom_11    0
Symptom_12    0
Symptom_13    0
Symptom_14    0
Symptom_15    0
Symptom_16    0
Symptom_17    0
dtype: int64

In [188]:
df["Disease"].nunique()

41

In [189]:
df["Disease"].value_counts()

Disease
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Allergy                                    120
hepatitis A                                120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
Impetigo                                   120
Name: count, dtype: int64

In [190]:
symptom_columns = [col for col in df.columns if col.lower().startswith("symptom_")]

all_symptoms = set()

for col in symptom_columns:
    all_symptoms.update(df[col].dropna().unique())

print("Total unique symptoms:", len(all_symptoms))

Total unique symptoms: 132

In [191]:
symptom_columns = [col for col in df.columns if col.lower().startswith("symptom_")]

duplicate_count = df[symptom_columns].duplicated().sum()

print("Jumlah data symptom duplikat:", duplicate_count)

Jumlah data symptom duplikat: 4616

# PREPROCESSING

In [192]:
symptom_columns = [col for col in df.columns if col.lower().startswith("symptom_")]

symptom_data = df[symptom_columns].values.tolist()

In [193]:
symptom_columns = [col for col in df.columns if col.lower().startswith("symptom_")]

def clean_value(x):
    if pd.isna(x):
        return None
    x = str(x)
    x = x.strip()                 # hapus spasi depan/belakang
    x = x.lower()                 # lowercase
    x = x.replace(" ", "_")       # spasi jadi underscore
    return x if x != "" else None # buang string kosong

for col in symptom_columns:
    df[col] = df[col].apply(clean_value)

In [194]:
symptom_data = []

for _, row in df[symptom_columns].iterrows():
    symptoms = [s for s in row if s is not None]
    symptom_data.append(symptoms)

In [195]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
X = mlb.fit_transform(symptom_data)

feature_names = mlb.classes_
print("Total clean symptoms:", len(feature_names))

Total clean symptoms: 131

In [196]:
y = df["Disease"]

In [197]:
print("Shape X:", X.shape)
print("Shape y:", y.shape)

Shape X: (4920, 131)
Shape y: (4920,)

In [198]:
X_df = pd.DataFrame(X, columns=feature_names)
X_df

,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,vomiting,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4916,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4918,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4919,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

# MODELLING

In [199]:
import numpy as np

X_aug = X.copy()

for i in range(len(X_aug)):
    ones_idx = np.where(X_aug[i] == 1)[0]
    if len(ones_idx) > 1:
        drop_idx = np.random.choice(ones_idx, size=1, replace=False)
        X_aug[i][drop_idx] = 0

In [200]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_aug, y,
    test_size=0.2,
    random_state=42,
    stratify=y  # penting untuk multiclass
)

In [201]:
# from sklearn.linear_model import LogisticRegression

# model = LogisticRegression(max_iter=500)
# model.fit(X_train, y_train)

In [202]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [203]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        24
                                   AIDS       1.00      1.00      1.00        24
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        24
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        24
                       Bronchial Asthma       1.00      1.00      1.00        24
                   Cervical spondylosis       1.00      1.00      1.00        24
                            Chicken pox       1.00      1.00      1.00        24
                    Chronic cholestasis       1.00      1.00      1.00        24
                            Common Cold       1.00      1.00      1.00        24
                                 Dengue       1.00      1.00      1.00        24
                              Diabetes        1.00      1.00      1.00        24
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        24
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        24
                                   GERD       1.00      1.00      1.00        24
                        Gastroenteritis       1.00      1.00      1.00        24
                           Heart attack       1.00      1.00      1.00        24
                            Hepatitis B       1.00      1.00      1.00        24
                            Hepatitis C       1.00      1.00      1.00        24
                            Hepatitis D       1.00      1.00      1.00        24
                            Hepatitis E       1.00      1.00      1.00        24
                          Hypertension        1.00      1.00      1.00        24
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        24
                         Hypothyroidism       1.00      1.00      1.00        24
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        24
                                Malaria       1.00      1.00      1.00        24
                               Migraine       1.00      1.00      1.00        24
                        Osteoarthristis       1.00      1.00      1.00        24
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        24
                              Pneumonia       1.00      1.00      1.00        24
                              Psoriasis       1.00      1.00      1.00        24
                           Tuberculosis       1.00      1.00      1.00        24
                                Typhoid       1.00      1.00      1.00        24
                Urinary tract infection       1.00      1.00      1.00        24
                         Varicose veins       1.00      1.00      1.00        24
                            hepatitis A       1.00      1.00      1.00        24

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

In [204]:
import numpy as np

probs = model.predict_proba(X_test)

# contoh lihat 1 sample
sample_probs = probs[0]

top3_idx = np.argsort(sample_probs)[-3:][::-1]

for idx in top3_idx:
    print(model.classes_[idx], sample_probs[idx])

Hypertension  1.0
hepatitis A 0.0
Common Cold 0.0

In [205]:
import joblib

joblib.dump(model, "disease_model.pkl")
joblib.dump(mlb, "symptom_encoder.pkl")

['symptom_encoder.pkl']

# TEST

In [206]:
import numpy as np
import joblib

def predict_disease(user_symptoms):
    model = joblib.load("disease_model.pkl")
    mlb = joblib.load("symptom_encoder.pkl")

    user_vector = mlb.transform([user_symptoms])

    probs = model.predict_proba(user_vector)[0]
    top_idx = np.argsort(probs)[-3:][::-1]

    results = []
    for idx in top_idx:
        results.append({
            "disease": model.classes_[idx],
            "probability": float(probs[idx])
        })

    return results

In [207]:
predict_disease(["high_fever", "cough", "headache", "fatigue"])

[{'disease': 'Bronchial Asthma', 'probability': 0.405},
 {'disease': 'Paralysis (brain hemorrhage)', 'probability': 0.135},
 {'disease': 'Malaria', 'probability': 0.09}]

In [208]:
user_symptoms = ["high_fever", "cough", "headache", "fatigue"]
user_vector = mlb.transform([user_symptoms])

print(user_vector.shape)   # harus (1, 132)
print(user_vector)

(1, 131)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

In [209]:
print(mlb.classes_)

['abdominal_pain' 'abnormal_menstruation' 'acidity' 'acute_liver_failure'
 'altered_sensorium' 'anxiety' 'back_pain' 'belly_pain' 'blackheads'
 'bladder_discomfort' 'blister' 'blood_in_sputum' 'bloody_stool'
 'blurred_and_distorted_vision' 'breathlessness' 'brittle_nails'
 'bruising' 'burning_micturition' 'chest_pain' 'chills'
 'cold_hands_and_feets' 'coma' 'congestion' 'constipation'
 'continuous_feel_of_urine' 'continuous_sneezing' 'cough' 'cramps'
 'dark_urine' 'dehydration' 'depression' 'diarrhoea' 'dischromic__patches'
 'distention_of_abdomen' 'dizziness' 'drying_and_tingling_lips'
 'enlarged_thyroid' 'excessive_hunger' 'extra_marital_contacts'
 'family_history' 'fast_heart_rate' 'fatigue' 'fluid_overload'
 'foul_smell_of_urine' 'headache' 'high_fever' 'hip_joint_pain'
 'history_of_alcohol_consumption' 'increased_appetite' 'indigestion'
 'inflammatory_nails' 'internal_itching' 'irregular_sugar_level'
 'irritability' 'irritation_in_anus' 'itching' 'joint_pain' 'knee_pain'
 'lack_of_concentration' 'lethargy' 'loss_of_appetite' 'loss_of_balance'
 'loss_of_smell' 'malaise' 'mild_fever' 'mood_swings' 'movement_stiffness'
 'mucoid_sputum' 'muscle_pain' 'muscle_wasting' 'muscle_weakness' 'nausea'
 'neck_pain' 'nodal_skin_eruptions' 'obesity' 'pain_behind_the_eyes'
 'pain_during_bowel_movements' 'pain_in_anal_region' 'painful_walking'
 'palpitations' 'passage_of_gases' 'patches_in_throat' 'phlegm' 'polyuria'
 'prominent_veins_on_calf' 'puffy_face_and_eyes' 'pus_filled_pimples'
 'receiving_blood_transfusion' 'receiving_unsterile_injections'
 'red_sore_around_nose' 'red_spots_over_body' 'redness_of_eyes'
 'restlessness' 'runny_nose' 'rusty_sputum' 'scurring' 'shivering'
 'silver_like_dusting' 'sinus_pressure' 'skin_peeling' 'skin_rash'
 'slurred_speech' 'small_dents_in_nails' 'spinning_movements'
 'spotting__urination' 'stiff_neck' 'stomach_bleeding' 'stomach_pain'
 'sunken_eyes' 'sweating' 'swelled_lymph_nodes' 'swelling_joints'
 'swelling_of_stomach' 'swollen_blood_vessels' 'swollen_extremeties'
 'swollen_legs' 'throat_irritation' 'toxic_look_(typhos)'
 'ulcers_on_tongue' 'unsteadiness' 'visual_disturbances' 'vomiting'
 'watering_from_eyes' 'weakness_in_limbs' 'weakness_of_one_body_side'
 'weight_gain' 'weight_loss' 'yellow_crust_ooze' 'yellow_urine'
 'yellowing_of_eyes' 'yellowish_skin']

In [211]:
def interpret_result(results):
    top_prob = results[0]['probability']
    
    if top_prob >= 0.7:
        return "single"
    elif top_prob >= 0.4:
        return "top3"
    else:
        return "ask_more"

In [2]:
import joblib

model = joblib.load("disease_model.pkl")
joblib.dump(model, "disease_model_compressed.pkl", compress=3)

c:\Users\acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.5.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.5.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

['disease_model_compressed.pkl']